#!/bin/sh
# netos-gcc - cc for netOS: C in, loadable b.out image out.
#   netos-gcc [cc flags] file.c ... [file.o] [-lfoo] -o prog
#   netos-gcc -c file.c [-o file.o]
set -e
P=/opt/i960
T=i960-intel-nindy
CC="$T-gcc -O2 -fno-common -D__netos__ -isystem $P/netos/include -isystem $P/netos/include/ncurses"
out= mode= flags= srcs= objs= libs=

while [ $# -gt 0 ]; do
	case "$1" in
	-o) out=$2; shift ;;
	-c|-S|-E|-M|-MM) mode=$1; flags="$flags $1" ;;
	-l*|-L*) libs="$libs $1" ;;
	-static|-s|-Wl,*) ;;
	*.c|*.s|*.S) srcs="$srcs $1" ;;
	*.o|*.a) objs="$objs $1" ;;
	*) flags="$flags $1" ;;
	esac
	shift
done
[ -n "$mode" ] && exec $CC $flags $srcs ${out:+-o "$out"}
[ -n "$srcs$objs" ] || exec $CC $flags

tmp=$(mktemp -d)
trap 'rm -rf $tmp' EXIT
n=0
for s in $srcs; do
	n=$((n + 1))
	$CC $flags -c -o $tmp/$n.o "$s"
	objs="$objs $tmp/$n.o"
done

$T-ld -r -o $tmp/link.rel -L$P/netos/lib -L$P/$T/lib $P/netos/lib/crt0.o $objs \
	--start-group $libs -lnetos -lc -lm -lgcc --end-group
u=$($T-nm -u $tmp/link.rel | awk '{print substr($NF, 2)}')
[ -z "$u" ] || { echo "netos-gcc: undefined:" $u >&2; exit 1; }
mkbout $tmp/link.rel "${out:-a.out}" _start
