/* rename libnetos's public symbols so the host test can link against glibc too */
#define printf np_printf
#define fprintf np_fprintf
#define sprintf np_sprintf
#define snprintf np_snprintf
#define vfprintf np_vfprintf
#define vsnprintf np_vsnprintf
#define puts np_puts
#define fputs np_fputs
#define fputc np_fputc
#define putchar np_putchar
#define fgetc np_fgetc
#define getchar np_getchar
#define fgets np_fgets
#define fread np_fread
#define fwrite np_fwrite
#define fopen np_fopen
#define fclose np_fclose
#define fflush np_fflush
#define feof np_feof
#define perror np_perror
#define malloc np_malloc
#define calloc np_calloc
#define realloc np_realloc
#define free np_free
#define exit np_exit
#define atoi np_atoi
#define atol np_atol
#define strtol np_strtol
#define abs np_abs
#define getenv np_getenv
#define rand np_rand
#define srand np_srand
#define strlen np_strlen
#define strcpy np_strcpy
#define strncpy np_strncpy
#define strcat np_strcat
#define strncat np_strncat
#define strcmp np_strcmp
#define strncmp np_strncmp
#define strchr np_strchr
#define strrchr np_strrchr
#define strstr np_strstr
#define memset np_memset
#define memcpy np_memcpy
#define memmove np_memmove
#define memcmp np_memcmp
#define bcopy np_bcopy
#define bzero np_bzero
#define open np_open
#define close np_close
#define read np_read
#define write np_write
#define lseek np_lseek
#define select np_select
#define usleep np_usleep
#define sleep np_sleep
#define time np_time
#define localtime np_localtime
#define stdin np_stdin
#define stdout np_stdout
#define stderr np_stderr
#define main np_main
