#ifndef _ERRNO_H
#define _ERRNO_H
/* netOS numbering, taken from the kernel's own errno name table */
extern int *__netos_errno;
#define errno (*__netos_errno)

#define EACCES		1
#define EADDRINUSE	2
#define EADDRNOTAVAIL	3
#define EAFNOSUPPORT	4
#define ECONNREFUSED	5
#define EDESTADDRREQ	6
#define EHOSTDOWN	7
#define EHOSTUNREACH	8
#define EINPROGRESS	9
#define EINVAL		10
#define EMSGSIZE	11
#define ENETUNREACH	12
#define ENOBUFS		13
#define ENOPROTOOPT	14
#define ENXIO		15
#define EOPNOTSUPP	16
#define ETIMEDOUT	17
#define EALREADY	18
#define ECONNRESET	20
#define EEXIST		22
#define EISCONN		23
#define ENETDOWN	24
#define ENOTCONN	25
#define EPERM		26
#define EPIPE		27
#define EPROTONOSUPPORT	28
#define EPROTOTYPE	29
#define ESRCH		30
#define EWOULDBLOCK	31
#define EBADF		32
#define EINTR		33
#define ENOENT		34
#define EMFILE		35
#define EBUSY		36
#define EAGAIN		37
#define EIO		38
#define ENOTTY		39
#define ENOMEM		40
#define EROFS		41
#define ENOTDIR		42
#define E2BIG		43
#define EFAULT		44
#define ENOEXEC		45
#define ECHILD		46
#define ERANGE		47
#define EDOM		48
#define ENAMETOOLONG	49
#define EPFNOSUPPORT	50
#define ESTALE		51
#define EREMOTE		52
#define ENODEV		53
#define EISDIR		54
#define EFBIG		55
#define ENOSPC		56
#define ENOTEMPTY	57
#define EDQUOT		58
#define ENETRESET	60
#define ETOOMANYREFS	61
#define EXDEV		63
#define ENFILE		68
#define ENOTBLK		69
#define EUSERS		70
#define EMLINK		71
#define ESPIPE		72
#define ELOOP		73
#define ESHUTDOWN	74
#define ENOTSOCK	75
#define ESOCKTNOSUPPORT	76
#endif
