#include <errno.h>

extern int *__netos_errno;

/* the kernel's errno numbers, in the order of its own name table */
static const unsigned char xerr[] = {
	0, EACCES, EADDRINUSE, EADDRNOTAVAIL, EAFNOSUPPORT, ECONNREFUSED,
	EDESTADDRREQ, EHOSTDOWN, EHOSTUNREACH, EINPROGRESS, EINVAL, EMSGSIZE,
	ENETUNREACH, ENOBUFS, ENOPROTOOPT, ENXIO, EOPNOTSUPP, ETIMEDOUT,
	EALREADY, EIO, ECONNRESET, EIO, EEXIST, EISCONN, ENETDOWN, ENOTCONN,
	EPERM, EPIPE, EPROTONOSUPPORT, EPROTOTYPE, ESRCH, EAGAIN, EBADF, EINTR,
	ENOENT, EMFILE, EBUSY, EAGAIN, EIO, ENOTTY, ENOMEM, EROFS, ENOTDIR,
	E2BIG, EFAULT, ENOEXEC, ECHILD, ERANGE, EDOM, ENAMETOOLONG,
	EPFNOSUPPORT, ESTALE, EIO, ENODEV, EISDIR, EFBIG, ENOSPC,
	ENOTEMPTY, EDQUOT, EIO, ENETRESET, ETOOMANYREFS, EIO, EXDEV, EIO, EIO,
	EIO, EIO, ENFILE, EINVAL, EIO, EMLINK, ESPIPE, ELOOP, EPIPE,
	ENOTSOCK, EPROTONOSUPPORT
};

int __netos_seterr(void)
{
	unsigned e = *__netos_errno;

	errno = e < sizeof xerr ? xerr[e] : EIO;
	return -1;
}
