#include <errno.h>
#include <string.h>

/* the netOS kernel's own names in errno order; one string, so no relocs */
static const char names[] =
	"no error\0EACCES\0EADDRINUSE\0EADDRNOTAVAIL\0EAFNOSUPPORT\0ECONNREFUSED\0"
	"EDESTADDRREQ\0EHOSTDOWN\0EHOSTUNREACH\0EINPROGRESS\0EINVAL\0EMSGSIZE\0"
	"ENETUNREACH\0ENOBUFS\0ENOPROTOOPT\0ENXIO\0EOPNOTSUPP\0ETIMEDOUT\0EALREADY\0"
	"\0ECONNRESET\0\0EEXIST\0EISCONN\0ENETDOWN\0ENOTCONN\0EPERM\0EPIPE\0"
	"EPROTONOSUPPORT\0EPROTOTYPE\0ESRCH\0EWOULDBLOCK\0EBADF\0EINTR\0ENOENT\0"
	"EMFILE\0EBUSY\0EAGAIN\0EIO\0ENOTTY\0ENOMEM\0EROFS\0ENOTDIR\0E2BIG\0EFAULT\0"
	"ENOEXEC\0ECHILD\0ERANGE\0EDOM\0ENAMETOOLONG\0EPFNOSUPPORT\0ESTALE\0EREMOTE\0"
	"ENODEV\0EISDIR\0EFBIG\0ENOSPC\0ENOTEMPTY\0EDQUOT\0EWFLUSH\0ENETRESET\0"
	"ETOOMANYREFS\0EBADRPC\0EXDEV\0EPROCUNAVAIL\0ERPCMISMATCH\0EPROGUNAVAIL\0"
	"EPROGMISMATCH\0ENFILE\0ENOTBLK\0EUSERS\0EMLINK\0ESPIPE\0ELOOP\0ESHUTDOWN\0"
	"ENOTSOCK\0ESOCKTNOSUPPORT\0";

char *strerror(int e)
{
	static char buf[20];
	const char *s = names;
	char *p = buf + sizeof buf;
	unsigned n = e;
	int i;

	for (i = 0; i < e && s < names + sizeof names - 1; i++)
		s += strlen(s) + 1;
	if (e >= 0 && s < names + sizeof names - 1 && *s) return (char *) s;
	*--p = 0;
	do *--p = (char) ('0' + n % 10); while (n /= 10);
	return memcpy(p - 6, "error ", 6);
}
